name: "beanieboi"
profile:
  web: "https://abwesend.com"
  twitter: "beanieboi"
  current_hometown: "Boston, MA, USA"
hasbeen:
  cities:
    - "Amsterdam, Netherlands"
    - "Barcelona, Spain"
    - "Berlin, Germany"
    - "Bilbao, Spain"
    - "Boston, MA, USA"
    - "Bratislava"
    - "Bremen, Germany"
    - "Brussels, Belgium"
    - "Buffalo, NY, USA"
    - "Burlington, VT, USA"
    - "Canoa, Ecuador"
    - "Cleveland, OH, USA"
    - "Dresden, Germany"
    - "Erie, PA, USA"
    - "Esbjerg, Denmark"
    - "Frankfurt, Germany"
    - "Garmisch-Partenkirchen, Germany"
    - "Grado, Italy"
    - "Graz, Austria"
    - "Haleiwa, HI, USA"
    - "Hallein, Austria"
    - "Hamburg, Germany"
    - "Helsinki, Finland"
    - "Honolulu, HI, USA"
    - "Innsbruck, Austria"
    - "Krakow, Poland"
    - "Las Tablas, Panama"
    - "Leipzig, Germany"
    - "Lincoln, NH, USA"
    - "Linz, Austria"
    - "London, Great Britain"
    - "Madrid, Spain"
    - "Mainz, Germany"
    - "Montréal, QB, Canada"
    - "Munich, Germany"
    - "New York City, NY, USA"
    - "Newport, RI, USA"
    - "Niagra Falls, NY, USA"
    - "Ottawa, QB, Canada"
    - "Panama City, Panama"
    - "Paris, France"
    - "Philadelphia, PA, USA"
    - "Pittsburg, PA, USA"
    - "Portland, ME, USA"
    - "Prague, Czech Republic"
    - "Prien am Chiemsee, Germany"
    - "Providence, RI, USA"
    - "Quebec City, QB, Canada"
    - "Quito, Ecuador"
    - "Saalbach-Hinterglem, Austria"
    - "Salzburg, Austria"
    - "San Antonio, TX, USA"
    - "San Blas Islands, Panama"
    - "San Francisco, CA, USA"
    - "San Sebastián, Spain"
    - "Seattle, WA, USA"
    - "Squamish, BC, Canada"
    - "St. Poelten, Austria"
    - "Toronto, ON, Canada"
    - "Trieste, Italy"
    - "Udine, Italy"
    - "Vancouver, BC, Canada"
    - "Vienna, Austria"
    - "Villach, Austria"
    - "Washington DC"
    - "Wiesbaden, Germany"
    - "Zadar, Croatia"
